### ISSUE TITLE
Make settings/controls scrollable

### ISSUE THREAD

**Issue by atjn** [atjn/blockchain-visualizer#47]
If users have small screens or use scaling, then the settings might be so long that they continue beyond the screen. There is currently no way for the user to access those settings.

It should be relatively easy to implement a scrollbar to allows the user to scroll from the top settings to the bottom settings.

![image](https://user-images.githubusercontent.com/20535393/168347301-ccac86d6-36b5-4f89-9103-542a3d322df6.png)

**Comment by lewisyng** [comment]
Hey, I'd like to fix this for you

**Comment by atjn** [comment]
Hey @lewisyng that would be great, thank you :)

Please check out our [CONTRIBUTING](https://github.com/atjn/blockchain-visualizer/blob/main/CONTRIBUTING.md) for more information.

**Comment by lewisyng** [comment]
@atjn Just added the scrollbar. Some checks don't seem to start automatically. Let me know if something is missing for that to happen
